// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cibstabibxrtrrklcdyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpYnN0YWJpYnhydHJya2xjZHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMjU3NDIsImV4cCI6MjA2MzcwMTc0Mn0.41avDE5LBZGgV7wnUH1vo1JCc9Ece7UD2llc1CnjSv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);